/**
* @author Sapient
* @date xx/xx/20xx
* @description <classDescription>
*/

public with sharing class {{ api_name }} {
	
	public {{ api_name }}() {
		
	}
	
	/*******************************************************************************************************
    * @description <methodDescription>
    * @param <parametereName> <parameterDescription>
    * @return <returnType>
    * @example
    * {{ api_name }}.method_one('test');    
    */
    public static <returnType> method_one(<parametereType> <parametereName>){
	
	}
	
}