/**
* @author Sapient
* @date xx/xx/20xx
* @description <classDescription>
*/

@isTest
private class {{ api_name }} {
	
	/*******************************************************************************************************
    * @description <methodDescription>    
    */
	@isTest static void positive_test_method() {
		// Implement test code
	}
	
	/*******************************************************************************************************
    * @description <methodDescription>  
    */
	@isTest static void negative_test_method() {
		// Implement test code
	}
	
}